// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSampleCSV():Promise<string>;

export function InspectCSV(arg1:string):Promise<main.CSVInfo>;

export function RunDemo(arg1:string,arg2:number):Promise<void>;

export function SelectCSV():Promise<string>;
