// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSampleCSV() {
  return window['go']['main']['App']['GetSampleCSV']();
}

export function InspectCSV(arg1) {
  return window['go']['main']['App']['InspectCSV'](arg1);
}

export function RunDemo(arg1, arg2) {
  return window['go']['main']['App']['RunDemo'](arg1, arg2);
}

export function SelectCSV() {
  return window['go']['main']['App']['SelectCSV']();
}
