<#
.SYNOPSIS
    Loads a recorded Jev fixture and registers it into the mock engine for offline replay.

.DESCRIPTION
    Reads a JSON fixture generated by Export-JevFixture and configures the mock
    engine to replay the exact answers and confidence values when evaluating matching
    questions.

.PARAMETER Path
    The file path to the JSON fixture.

.EXAMPLE
    Import-JevFixture -Path .\fixtures\billing_triage.json
#>
function Import-JevFixture {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory, ValueFromPipeline, Position = 0)]
        [string] $Path
    )

    process {
        if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
            throw "Fixture file not found: $Path"
        }

        $content = Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json
        if (-not $content.response -or -not $content.response.answers) {
            throw "Invalid fixture format in '$Path': missing response.answers."
        }

        $answers = $content.response.answers
        $registered = [System.Collections.Generic.List[object]]::new()

        foreach ($prop in $answers.PSObject.Properties) {
            $qName = $prop.Name
            $ans = $prop.Value
            $ansType = ([string] $ans.type).ToLowerInvariant()
            $ruleVal = $null
            $conf = 0.95

            switch ($ansType) {
                'noul' {
                    $ruleVal = [double] $ans.noul
                }
                'choice' {
                    $ruleVal = [string] $ans.choice
                    if ($ans.PSObject.Properties['confidence']) { $conf = [double] $ans.confidence }
                }
                'score' {
                    $ruleVal = [double] $ans.score
                    if ($ans.PSObject.Properties['confidence']) { $conf = [double] $ans.confidence }
                }
            }

            if ($null -ne $ruleVal) {
                $rule = Set-JevMockRule -QuestionName $qName -Matcher { $true } -Answer $ruleVal -Confidence $conf
                $registered.Add($rule)
            }
        }

        $registered.ToArray()
    }
}
